export const MODIFICAR_NOMBRE = 'MODIFICAR_NOMBRE';
export const MODIFICAR_DIRECCION = 'MODIFICAR_DIRECCION';
export const MODIFICAR_CATEGORIA = 'MODIFICAR_CATEGORIA';
export const MODIFICAR_DATOS = 'MODIFICAR_DATOS';
export const CARGAR_EMPRESAS = 'CARGAR_EMPRESAS';
export const SET_STATUS = 'SET_STATUS';